### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by yonkeltron** [moul/node-gitlab#196]
Hello,

I would love to use this library in a TypeScript project but it seems that [the only type definitions](https://www.npmjs.com/package/@types/gitlab) are third-party and woefully outdated. Any chance of getting official TypeScript support in the project?

Thanks,
+Jonathan

**Comment by Arylo** [comment]
it is suggested that you submit this issue to <https://github.com/jdalrymple/node-gitlab>

**Comment by yonkeltron** [comment]
Thanks, will do!
