### ISSUE TITLE
Archive this repository / move jdalrymple/node-gitlab here

### ISSUE THREAD

**Issue by max-wittig** [moul/node-gitlab#201]
This repository is always the first hit on Google.

https://github.com/jdalrymple/node-gitlab doesn't even appear.

So we either 
* need to archive this repository and add a link to jdalrymple/node-gitlab at the top
* or move `jdalrymple/node-gitlab` to here

@jdalrymple @moul

**Comment by jdalrymple** [comment]
This was discussed but never done :( #191

**Comment by moul** [comment]
👍 I added you as co-owner of the node-gitlab organization, I will rename & archive this repo so you can move yours here :)

good luck everyone, thank you @dave-irvine for your support during these years
